### ISSUE TITLE
[BUG] KnowledgeBaseTool may return parameter placeholder not filled error

### ISSUE THREAD

**Issue by yuye-aws** [opensearch-project/ml-commons#2712]
**What is the bug?**
I am implementing the the knowledge base tool. Unfortunately, I meet with a tricky bug from the connector. I did some deep dive and found the error is originating from `validatePayload` function from `Connector.java`.

**How can one reproduce the bug?**
Prerequisites: configure LLM and bedrock knowledge base, and then obtain their `model_id`.

1. Register the agent with knowledge base tool.
```
POST /_plugins/_ml/agents/_register
{
  "name": "Test_Agent_For_ReAct_KB",
  "type": "conversational",
  "description": "this is a test agent for knowledge base",
  "llm": {
    "model_id": "rBZl3pABQHtbJkH1MFP3",
    "parameters": {
      "max_iteration": 10,
      "stop_when_no_tool_found": true,
      "response_filter": "$.completion"
    }
  },
  "memory": {
    "type": "conversation_index"
  },
  "tools": [
    {
      "type": "KnowledgeBaseTool",
      "name": "OpensearchKnowledgeBaseTool",
      "description": "A tool to search the Opensearch knowledge base, the knowledge base consists of segments of OpenSearch documents. You should always search data with this tool when encountering general questions about Opensearch. But for questions about current concerete cluster, use this tool can not help you. If this tool provides useful info, give the answer and also quote the origin doc. If this tool can not provide knowledge you need, give answer based on your own knowledge. Action Input: {\"text\": <natrual language keywords for question>}",
      "parameters": {
        "model_id": "phZk3pABQHtbJkH1fVPy"
      }
    },
    {
      "type": "CatIndexTool",
      "name": "RetrieveIndexMetaTool",
      "description": "Use this tool to get OpenSearch index information: (health, status, index, uuid, primary count, replica count, docs.count, docs.deleted, store.size, primary.store.size)."
    }
  ],
  "app_type": "my app"
}

```

2. Execute the agent to retrieve documents on "agent framework".
```
POST /_plugins/_ml/agents/_haq3pABQHtbJkH1eVNE/_execute
{
  "parameters": {
    "question": "Use OpensearchKnowledgeBaseTool to get information about agent framework in opensearch",
    "verbose": true
  }
}
```

3. Receive the following error:
```
"{\"error\":{\"reason\":\"Invalid Request\",\"details\":\"Some parameter placeholder not filled in payload: VectorDBTool.output\",\"type\":\"IllegalArgumentException\"},\"status\":400}"
```
**What is the expected behavior?**
The retrieved documents from bedrock knowledge should be free from payload validation in connector. 

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by yuye-aws** [comment]
Here is one of the documents retrieved from the knowledge base. The substring `${parameters.VectorDBTool.output}` matches the regex `"\\$\\{parameters\\.([^}]+)}"` in https://github.com/opensearch-project/ml-commons/blob/9b413a7212743a7820ab2dfb61b3c4b88ead2e12/common/src/main/java/org/opensearch/ml/common/connector/Connector.java#L82
```
\n\n Context:\n${parameters.VectorDBTool.output}\n\nHuman:Use OpensearchKnowledgeBaseTool to get information about agent framework in opensearch\n\nAssistant:"       }     }   ] } ``` {% include copy-curl.html %}  OpenSearch returns an agent ID for the newly created agent:  ```json {   "agent_id": "879v9YwBjWKCe6Kg12Tx" } ```  You can inspect the agent by sending a request to the `agents` endpoint and providing the agent ID:  ```json GET \/_plugins\/_ml\/agents\/879v9YwBjWKCe6Kg12Tx ``` {% include copy-curl.html %}  To execute the agent, send the following request. When registering the agent, you configured it to take in `parameters.question`, so you need to provide this parameter in the request.
```

**Comment by yuye-aws** [comment]
This function may wrongly replace parameters from returned body:
https://github.com/opensearch-project/ml-commons/blob/9b413a7212743a7820ab2dfb61b3c4b88ead2e12/common/src/main/java/org/opensearch/ml/common/connector/HttpConnector.java#L311

**Comment by yuye-aws** [comment]
Notice that the prompt for LLM may contain strings like ${parameters.foo}. Raised a PR to fix it: https://github.com/opensearch-project/ml-commons/pull/2724

**Comment by jngz-es** [comment]
Correct me, if I misunderstand. You mean the output of KnowledgeBaseTool can contain something like the string "`${parameters.VectorDBTool.output}`", right?

**Comment by yuye-aws** [comment]
> Correct me, if I misunderstand. You mean the output of KnowledgeBaseTool can contain something like the string "`${parameters.VectorDBTool.output}`", right?

Yes.

**Comment by yuye-aws** [comment]
The bug also persists with remote LLM connector:

```
POST /_plugins/_ml/models/<remote_llm_model_id>/_predict/
{
  "parameters": {
    "prompt": """Human: What is ${parameters.foo} \n Assistant:"""
  }
}
```

And receives error

```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Some parameter placeholder not filled in payload: foo"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "Some parameter placeholder not filled in payload: foo"
  },
  "status": 400
}
```

**Comment by yuye-aws** [comment]
Created an RFC as a solution: https://github.com/opensearch-project/ml-commons/issues/2748

**Comment by Prabhu2397** [comment]
# Bug Report: `text_embedding` processor fails to serialize field content for remote connector (`placeholder not filled`) in OpenSearch 2.19

### Component

*   **ML-Commons** (`text_embedding` ingest processor)
*   Remote Connector (GCP Vertex AI Blueprint)

### OpenSearch Version

`2.19.0` (Please verify your exact version)

### Description

We are blocked from using the `text_embedding` ingest processor with a custom remote connector (based on the GCP Vertex AI blueprint) because the processor fails to populate the required parameter placeholder.

The model is deployed successfully, and the connector is validated via the `_predict` API. However, when running the ingest pipeline (via `_simulate`), the `text_embedding` processor consistently fails with an `illegal_argument_exception` indicating that the parameter placeholder is **not filled**, even though the source field is present in the document.

This strongly suggests a **serialization failure** within the `text_embedding` processor, where it fails to extract the text content from the document field (`field_map` key) and pass a non-empty value to the remote payload.

### Steps to Reproduce

1.  **Register and Deploy Model/Connector:**
    The connector was deployed, configured to use the blueprint's standard **`text_docs`** parameter.

    **Connector `request_body` Configuration (Latest Deployment):**
    ```json
    "request_body": "{\"instances\": [{ \"content\": \"${parameters.text_docs}\"}]}"
    ```
    (Note: This is the result of troubleshooting, as initial attempts with `prompt` and `text_input` failed identically, only changing the name of the missing placeholder in the error.)

2.  **Create Ingest Pipeline:**
    The pipeline is a direct implementation of the `text_embedding` processor.

    **Ingest Pipeline:**
    ```json
    {
      "description": "A vector ingest pipeline",
      "processors": [
        {
          "text_embedding": {
            "model_id": "<MODEL_ID_USED_IN_PIPELINE>",
            "field_map": {
              "sourceDescription": "source_description_embedding"
            }
          }
        }
      ]
    }
    ```

3.  **Simulate Pipeline Execution:**
    The pipeline was simulated using a document that explicitly contains the source field.

    **Simulate Request Data:**
    ```json
    {
      "docs": [
        {
          "_source": {
            "sourceDescription": "This is the text I want to embed."
          }
        }
      ]
    }
    ```

### Expected Behavior

The `text_embedding` processor should successfully extract the text from the `sourceDescription` field and use it to fill the `${parameters.text_docs}` placeholder in the remote connector payload, resulting in a successful embedding.

### Actual Behavior (Error)

The `text_embedding` processor fails with the following error, indicating the content for the `text_docs` placeholder is empty/null, despite the field being present in the `_source` of the document:

```json
{
    "docs": [
        {
            "processor_results": [
                {
                    "processor_type": "text_embedding",
                    "status": "error",
                    "error": {
                        "root_cause": [
                            {
                                "type": "illegal_argument_exception",
                                "reason": "Some parameter placeholder not filled in payload: text_docs"
                            }
                        ],
                        "type": "illegal_argument_exception",
                        "reason": "Some parameter placeholder not filled in payload: text_docs"
                    }
                }
            ]
        }
    ]
}
```

### Additional Context

*   **`_predict` API Works:** A direct `_predict` call to the same model using a simple single parameter is successful, validating the model and connector logic:
    ```bash
    POST /_plugins/_ml/models/<MODEL_ID_USED_IN_PREDICT>/_predict
    {"parameters": {"text_input": "Hello World form vertex AI!"}}
    // -> Returns a 200 SUCCESS with the embedding vector.
    ```
*   **Unsupported Configuration:** The parameter `input_field_name` is **unsupported** in this OpenSearch version, blocking a potential configuration workaround to explicitly set the parameter name sent by the processor.
