### ISSUE TITLE
[BUG] Bedrock multimodal model interface can't work with neural search

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/ml-commons#3261]
**What is the bug?**
Model interface for Bedrock multi-modal model can't work with neural search 

**How can one reproduce the bug?**
1. Create connector and model following this [blueprint](https://github.com/opensearch-project/ml-commons/blob/main/docs/remote_inference_blueprints/bedrock_connector_titan_multimodal_embedding_blueprint.md) 
2. Create ingest pipeline and try to ingest doc following this [doc](https://opensearch.org/docs/latest/search-plugins/multimodal-search/) , then can see such error when ingest doc

```
PUT /my-nlp-index/_doc/1
{
 "image_description": "Orange table"
}
```
error
```
{
  "error": {
    "root_cause": [
      {
        "type": "status_exception",
        "reason": "Error validating input schema: Validation failed: [$: required property 'parameters' not found] for instance: {\"algorithm\":\"REMOTE\",\"text_docs\":[\"Orange table\"],\"return_bytes\":false,\"return_number\":true,\"target_response\":[\"sentence_embedding\"]} with schema: {\n    \"type\": \"object\",\n    \"properties\": {\n        \"parameters\": {\n            \"type\": \"object\",\n            \"properties\": {\n                \"inputText\": {\n                    \"type\": \"string\"\n                },\n                \"inputImage\": {\n                    \"type\": \"string\"\n                }\n            }\n        }\n    },\n    \"required\": [\n        \"parameters\"\n    ]\n}"
      }
    ],
    "type": "status_exception",
    "reason": "Error validating input schema: Validation failed: [$: required property 'parameters' not found] for instance: {\"algorithm\":\"REMOTE\",\"text_docs\":[\"Orange table\"],\"return_bytes\":false,\"return_number\":true,\"target_response\":[\"sentence_embedding\"]} with schema: {\n    \"type\": \"object\",\n    \"properties\": {\n        \"parameters\": {\n            \"type\": \"object\",\n            \"properties\": {\n                \"inputText\": {\n                    \"type\": \"string\"\n                },\n                \"inputImage\": {\n                    \"type\": \"string\"\n                }\n            }\n        }\n    },\n    \"required\": [\n        \"parameters\"\n    ]\n}"
  },
  "status": 400
}
```

**What is the expected behavior?**
This is a break change. We should not break BWC by introducing model interface. 

**What is your host/environment?**
 - OS: Linux
 - Version 2.17.1
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by maltelorbach** [comment]
Same behaviour in 2.18.0.

Digging into the code, I think the issue is the algorithm type used by the `text_image_embedding` processor. It uses a hardcoded value `FunctionName.TEXT_EMBEDDING` when instantiating the `MLInput` here:
https://github.com/opensearch-project/neural-search/blob/7feacd67b3c7694ff4a1c1c2b430f2447a1ed4ab/src/main/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessor.java#L293

but for Bedrock (and possibly others), the algorithm type should be `FunctionName.REMOTE` such that the inputs are parsed from `parameters`:
https://github.com/opensearch-project/ml-commons/blob/c2a40c195402827fc5f113b865c12701f76fa60a/common/src/main/java/org/opensearch/ml/common/input/MLInput.java#L203-L206

**Comment by b4sjoo** [comment]
Nice catch, @maltelorbach ! I will take a look and see if I can submit a fix
