### ISSUE TITLE
[BUG] model search doesn't recognize _source field

### ISSUE THREAD

**Issue by wanglam** [opensearch-project/ml-commons#419]
**What is the bug?**
I am using the model search API to get all trained model. But the API still response all fields even I pass _source field in the query body. The query like:

```
POST /_plugins/_ml/models/_search
{
  "_source": ["name"],
  "query":{
    "match_all":{
      
    }
  }
}
```

**How can one reproduce the bug?**
Just use query like
```
POST /_plugins/_ml/models/_search
{
  "_source": ["name"],
  "query":{
    "match_all":{
      
    }
  }
}
```

**What is the expected behavior?**
Should only response name field in the response _source.

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**
![image](https://user-images.githubusercontent.com/4034161/189296852-e128495d-aeaa-451f-90fa-637f7ea1a387.png)
The model_content field is also returned.

**Do you have any additional context?**
Nope.

**Comment by ylwu-amzn** [comment]
Thanks for reporting this bug. This is caused by source context rewrite in [AbstractMLSearchAction.java](https://github.com/opensearch-project/ml-commons/blob/main/plugin/src/main/java/org/opensearch/ml/rest/AbstractMLSearchAction.java#L47). We should keep original fetch source in method `getSourceContext`

@rbhavna can you help fix this bug?
